### ISSUE TITLE
用 code 控制 bone

### ISSUE THREAD

**Issue by cwoandrew** [BobSongCN/spine-egret-runtimes#2]
在 spine 我加了 3 支 bone 2 支有 animation key ， 1 支没有，没有 key 的 bone 我叫它 "otherBone"，想用 code 控制

let bone = this.spineTestFile.skeleton.findBone("otherBone");
bone.scaleX = bone.scaleY = 2;
bone.y = -500;

這樣可以把 "otherBone" 放大放好，但只要 play animation( "otherBone" 没有 animation key)，"otherBone" 就 reset 到原有的位置和大小了，是不是錯了什麼?

**Comment by BobSongCN** [comment]
因为你的动画里有控制，所以被动画给还原了

**Comment by cwoandrew** [comment]
但在 spine 中這支骨没有任何 key 的，是 export 問題?

**Comment by BobSongCN** [comment]
这个我就不确定了。我没做过这种操作。核心控制是spine的代码的，我主要就是完善了下白鹭的渲染。具体的控制逻辑我不是很了解的
